# Generated by Django 2.2.7 on 2019-11-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedictapp', '0002_authgrouppermissions_authpermission_authuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
